### ISSUE TITLE
Tutorial sobre el Uso de OpenCV

### ISSUE THREAD

**Issue by MordodeMaru** [biicode/docs#162]
Hay que escribir en Mardown un tutorial sobre como usar OpenCV en biicode. Debajo tienes las intrucciones del equipo OpenCV:

What I can suggest is that we have a bunch of tutorials (http://docs.opencv.org/ref/master/d9/df8/tutorial_root.html), some of them have been contributed from our users, like this one from Microsoft research guys: http://docs.opencv.org/ref/master/d4/d14/tutorial_windows_visual_studio_image_watch.html

We encourage you to write (using very simple Markdown format) and submit such a tutorial, and then it will be available to our users. At least it will be persistent reminder that there is such tool that they can use.

The tutorial sources are here: https://github.com/Itseez/opencv/tree/master/doc/tutorials
and here is the guide on how to contribute new code/docs to opencv: http://code.opencv.org/projects/opencv/wiki/How_to_contribute

**Comment by MariadeAnton** [comment]
@danimtb - el lunes lo vemos ^^

**Comment by danimtb** [comment]
Hecho el pull request con el tutorial
